### ISSUE TITLE
roi_helpers.py的115行报错

### ISSUE THREAD

**Issue by helloworld8710** [bubbliiiing/faster-rcnn-keras#11]
8/2000 [..............................] - ETA: 2:14:03 - rpn_cls: 2.5315 - rpn_regr: 3.9138 - detector_cls: 1.7752 - detector_regr: 0.4206Traceback (most recent call last):
  File "f:/deeplearning-exp/faster-rcnn-keras-master/train.py", line 119, in <module>
    X2, Y1, Y2, IouS = calc_iou(R, config, boxes[0], width, height, NUM_CLASSES)
  File "f:\deeplearning-exp\faster-rcnn-keras-master\utils\roi_helpers.py", line 115, in calc_iou
    Y2 = np.concatenate([np.array(y_class_regr_label),np.array(y_class_regr_coords)],axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
这一行似乎应该改成Y2 = np.concatenate([np.array(y_class_regr_label),np.array(y_class_regr_coords)],axis=0)，是么？

**Comment by helloworld8710** [comment]
还是因为数据输入有问题呢？否则，能开始训练，但是在训练几步之后才出问题。又试了几次，有些能训练的次数更多，可是也还是同样的错误。大神能帮忙看下是啥原因么？或者需要检查些什么呢？
  31/2000 [..............................] - ETA: 4:46:13 - rpn_cls: 1.4517 - rpn_regr: 5.4594 - detector_cls: 1.6543 - detector_regr: 0.1955Traceback (most recent call last):
  File "f:/deeplearning-exp/faster-rcnn-keras-master/train.py", line 119, in <module>
    X2, Y1, Y2, IouS = calc_iou(R, config, boxes[0], width, height, NUM_CLASSES)
  File "f:\deeplearning-exp\faster-rcnn-keras-master\utils_frcnn\roi_helpers.py", line 115, in calc_iou
    Y2 = np.concatenate([np.array(y_class_regr_label),np.array(y_class_regr_coords)],axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

**Comment by helloworld8710** [comment]
找到原因了，train.py文件中的NUM_CLASSES = 6+1的值，应该是类别值加上1，即加上背景后的类别数。
