### ISSUE TITLE
训练自己数据集时候遇到问题，麻烦博主看一下

### ISSUE THREAD

**Issue by JinHisAndy** [bubbliiiing/faster-rcnn-keras#38]
Epoch 1/50:   0%|          | 0/114 [00:04<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "F:/JetBrains/PycharmProjects/faster-rcnn-keras/train.py", line 208, in <module>
    callback)
  File "F:/JetBrains/PycharmProjects/faster-rcnn-keras/train.py", line 52, in fit_one_epoch
    X2, Y1, Y2 = calc_iou(R, config, boxes[i], NUM_CLASSES)
  File "F:\JetBrains\PycharmProjects\faster-rcnn-keras\utils\roi_helpers.py", line 122, in calc_iou
    np.int32)] = 1
IndexError: index 1 is out of bounds for axis 1 with size 1

就是这行代码：
y_class_regr_label[
        np.arange(np.shape(gt_roi_loc)[0])[:pos_roi_per_this_image], np.array(gt_roi_label[:pos_roi_per_this_image],
                                                                        np.int32)] = 1

**Comment by bubbliiiing** [comment]
classes设置错误应该，超出num_classes的范围
